version: "3"

services:
  web:
    restart: always
    build:
      context: ./web
      args:
        unbuffered: 0
        uncached: 0
    expose:
      - "8000"
    volumes:
      - /home/django/app
      - static:/home/django/app/static
    env_file: .env
    command: /home/django/.local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    depends_on:
      - postgres
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static:ro
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
  static:
