# Generated by Django 2.0.5 on 2018-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankmessagechat',
            name='thanked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thankmessagechatthread',
            name='thanked',
            field=models.BooleanField(default=False),
        ),
    ]
