# Generated by Django 2.0.5 on 2018-12-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20181125_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoomOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.ChatRoom')),
            ],
        ),
    ]
